name: Deployment for the selected brand

env:
  INVALIDATE_REQUIRED: false

on: 
  workflow_dispatch:
    inputs:
      remote:
        type: choice
        description: 'Select a remote'
        required: true
        options:
          - 24casino
          - 24pokies
          - 4crownscasino
          - arescasino
          - bigwins
          - casinohermes
          - cherryfiesta
          - chilli777
          - europe777
          - fireslots
          - goldenwin
          - goldenpharaoh
          - iwinfortune
          - lovecasino
          - luckywins
          - magicwin
          - maximalwin
          - mrsloty
          - oceanbreeze
          - rougecasino
          - spicyjackpots
          - spinsdeluxe
          - superb
          - winnercasino
          - bigacasino
          - luckycharms

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to brand
        run: |
          case ${{ github.event.inputs.remote }} in
            24casino)
              host="git@172.16.0.116"
              ;;
            24pokies)
              host="git@172.16.0.118"
              ;;
            4crownscasino)
              host="git@172.16.0.110"
              ;;
            arescasino)
              host="git@172.16.0.47"
              ;;
            bigwins)
              host="git@172.16.0.33"
              ;;
            casinohermes)
              host="git@172.16.0.52"
              ;;
            cherryfiesta)
              host="git@172.16.0.139"
              ;;
            chilli777)
              host="git@172.16.0.129"
              ;;
            europe777)
              host="git@172.16.0.51"
              ;;
            fireslots)
              host="git@172.16.0.48"
              ;;
            goldenwin)
              host="git@172.16.0.10"
              ;;
            goldenpharaoh)
              host="git@172.16.0.45"
              ;;
            iwinfortune)
              host="git@172.16.0.95"
              ;;
            lovecasino)
              host="git@172.16.0.39"
              ;;
            luckywins)
              host="git@172.16.0.81"
              ;;
            magicwin)
              host="git@172.16.0.91"
              ;;
            maximalwin)
              host="git@172.16.0.103"
              ;;
            mrsloty)
              host="git@172.16.0.132"
              ;;
            oceanbreeze)
              host="git@172.16.0.115"
              ;;
            rougecasino)
              host="git@172.16.0.131"
              ;;
            spicyjackpots)
              host="git@172.16.0.6"
              ;;
            spinsdeluxe)
              host="git@172.16.0.102"
              ;;
            superb)
              host="git@172.16.0.44"
              ;;
            winnercasino)
              host="git@172.16.0.106"
              ;;
            bigacasino)
              host="git@172.16.0.108"
              ;;
            luckycharms)
              host="git@172.16.0.2"
              ;;
            *)
              echo "Invalid remote selected"
              exit 1
              ;;
          esac
          echo "${{ github.event.inputs.remote }} "
          echo "$host"
          echo "==================================="

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check for changes in specific folders
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for file in $changed_files; do
            if [[ $file == scripts/* ]]; then
              echo "JavaScript files have changed, cache invalidation is required."
              echo "INVALIDATE_REQUIRED=true" >> "$GITHUB_ENV"
              break
            fi
          done

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y
        if: ${{ env.INVALIDATE_REQUIRED == true }}
