name: Rollback
run-name: Rollback apps by @${{ github.actor }}
on:
  workflow_dispatch:
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get latest tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LAST_TAG=$TAG" >> $GITHUB_ENV

      - name: Count changed files in a specific directory
        run: |
          file_count=$(git diff ${{ github.ref_name }} ${{ env.LAST_TAG }} -- scripts/ | wc -l)
          echo "Number of changed files: $file_count"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
