name: Rollback
run-name: Rollback apps by @${{ github.actor }}
on:
  workflow_dispatch:
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get latest tag
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Last tag is $LAST_TAG"

      - name: Compare tags in a specific directory
        run: git diff ${{ github.ref_name }} $LAST_TAG -- scripts/

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
