name: Rollback
run-name: Rollback apps by @${{ github.actor }}
on:
  workflow_dispatch:
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get latest tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LAST_TAG=$TAG" >> $GITHUB_ENV

      - name: Count changed files in a migration directory
        if: ${{ github.ref_name != env.LAST_TAG }}
        run: |
          FILE_COUNT=$(git diff --name-only ${{ github.ref_name }} ${{ env.LAST_TAG }} -- scripts/ | wc -l)
          echo "MIGRATION_NUMBER=$FILE_COUNT" >> $GITHUB_ENV

      - name: Get previous tag
        run: |
          git fetch --tags
          PREVIOUS=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          echo "PREVIOUS_TAG=$PREVIOUS" >> $GITHUB_ENV

      - name: Get LL
        run: |
          echo $(git log --oneline)
          echo "LL=$(git log --merges --min-parents=1 ${{ env.PREVIOUS_TAG }}..main --pretty=format:"%s" | sed -E 's/\(#([0-9]+)\)/(<https:\/\/github.com\/zogomarket\/betproduction-api\/pull\/\1|#\1>)/g')" >> $GITHUB_ENV
          echo "LL: ${{ env.LL }}"
          
      - name: Get PRs
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"blocks":[{"type":"header","text":{"type":"plain_text","text":"New release ${{ github.ref_name }} - api","emoji":true}},{"type":"section","text":{"type":"mrkdwn","text":"$(git log --oneline --min-parents=1 ${{ env.PREVIOUS_TAG }}..main --pretty=format:"%s" | sed -E 's/\(#([0-9]+)\)/(<https:\/\/github.com\/zogomarket\/betproduction-api\/pull\/\1|#\1>)/g')"}}]}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
