name: Create new version
run-name: Create new version by @${{ github.actor }}
on:
  push:
    tags: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JENKINS_USER: ${{ secrets.JENKINS_USER }}

    steps:
      - name: Run Jenkins job
        run: |
          curl -X POST -L --user ${{ env.JENKINS_USER }} https://jenkins.77dev.io/job/infra/job/create-container-ibet-api/buildWithParameters --data gitBranch='${{ github.ref }}'
